name: benford
channels:
  - conda-forge
dependencies:
  - python=3.12
  - icecream
  - matplotlib
  - numpy
  - opencv
  - scipy
  - ipykernel # you may add Jupyter if you use that, I'm using VS Code and thus only require the kernel