[project]
name = "Benfords-Law"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel",
    "icecream",
    "tqdm",
    
    "matplotlib",
    "numpy",
    "pillow",
    "scipy",

    "imageforensics",
]

[tool.uv]
python-preference = "only-managed"

[tool.uv.sources]
imageforensics = { path = "modules", editable = true }
